AWSTemplateFormatVersion: '2010-09-09'
Description : Basic S3 provisioning script

Resources : 
    MyS3Bucket:
        Type: AWS::S3::Bucket
        Properties: 
            VersioningConfiguration:
                Status: Enabled
            Tags:
              - Key: Env 
                Value: Dev
              - Key: Project 
                Value: CloudFormation-Practice

