AWSTemplateFormatVersion: "2010-09-09"
Description: "Application stack"
Resources:
  MySecurityGroup: 
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH access"
      VpcId: 
        Fn::ImportValue: VpcId    
 